[project]
name = "batch-asr"
version = "0.1.0"
description = "Transcribe speech 100x faster and 100x cheaper with Modal and NeMo ASR models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "modal>=1.0.5",
]
